// <auto-generated />
namespace EmployeeManagementSystem.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class JobVacancy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JobVacancy));
        
        string IMigrationMetadata.Id
        {
            get { return "202109281611537_JobVacancy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
